//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grafik
    {
        public int GrafikID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime Data_Start { get; set; }
        public System.DateTime Date_End { get; set; }
    
        public virtual Employ Employ { get; set; }
    }
}
