//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Uchet_cons = new HashSet<Uchet_cons>();
        }
    
        public int InvoiceID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Col_vo { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Employ Employ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uchet_cons> Uchet_cons { get; set; }
    }
}
