//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchet_cons
    {
        public int Uchet_consID { get; set; }
        public int ConsID { get; set; }
        public int InvoiceID { get; set; }
        public int Ostatki { get; set; }
    
        public virtual Consumables Consumables { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
