//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int VisitsID { get; set; }
        public int ClientID { get; set; }
        public int ServisID { get; set; }
        public System.DateTime DateVisit { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Services Services { get; set; }
    }
}
